import json

notebook_path = "/home/jonas/Documents/GitHub/HarmonicFermions/Jupyter/BaxterMeth-opt.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

new_source = [
    "import numba\n",
    "import os\n",
    "import math\n",
    "import numpy as np\n",
    "\n",
    "@numba.njit\n",
    "def logsumexp2(x, y):\n",
    "    m = x if x > y else y\n",
    "    return m + math.log(math.exp(x - m) + math.exp(y - m))\n",
    "\n",
    "@numba.njit\n",
    "def logsumexp_array(vals):\n",
    "    # Numba optimized version of logsumexp_list\n",
    "    m = np.max(vals)\n",
    "    s = 0.0\n",
    "    for i in range(len(vals)):\n",
    "        s += math.exp(vals[i] - m)\n",
    "    return m + math.log(s)\n",
    "\n",
    "@numba.njit\n",
    "def log1mexp_neg(x):\n",
    "    # x <= 0 ; returns log(1 - exp(x)) stably\n",
    "    return math.log(-math.expm1(x))\n",
    "\n",
    "@numba.njit\n",
    "def _log_Q_chunk(m_start, m_end, logb, L_prev, L):\n",
    "    for m in range(m_start, m_end):\n",
    "        L[m - 1] = logsumexp_array(L_prev[:m - 1])\n",
    "        log1mbpow = log1mexp_neg((m - 1) * logb)\n",
    "        for i in range(m - 1, 0, -1):\n",
    "            t1 = logb + L[i]\n",
    "            t2 = (1 - i) * logb + log1mbpow + L_prev[i - 1]\n",
    "            L[i - 1] = logsumexp2(t1, t2)\n",
    "        temp = L_prev\n",
    "        L_prev = L\n",
    "        L = temp\n",
    "    return L_prev, L\n",
    "\n",
    "@numba.njit\n",
    "def _compute_log_poch(n, logb):\n",
    "    log_poch = 0.0\n",
    "    for k in range(1, n + 1):\n",
    "        log_poch += log1mexp_neg(k * logb)\n",
    "    return log_poch\n",
    "\n",
    "def log_Q(n, b):\n",
    "    if not (0.0 < b < 1.0):\n",
    "        raise ValueError(\"b must lie in (0,1)\")\n",
    "    logb = math.log(b)\n",
    "    filename = f\"log_Q_n_{n}_b_{b}.npz\"\n",
    "    if os.path.exists(filename):\n",
    "        try:\n",
    "            data = np.load(filename)\n",
    "            m_start = int(data['m_start'])\n",
    "            L_prev = data['L_prev']\n",
    "            L = data['L']\n",
    "        except Exception:\n",
    "            m_start = 2\n",
    "            L_prev = np.zeros(n + 2, dtype=np.float64)\n",
    "            L = np.zeros(n + 2, dtype=np.float64)\n",
    "    else:\n",
    "        m_start = 2\n",
    "        L_prev = np.zeros(n + 2, dtype=np.float64)\n",
    "        L = np.zeros(n + 2, dtype=np.float64)\n",
    "\n",
    "    chunk_size = 50000\n",
    "    while m_start < n + 2:\n",
    "        m_end = min(m_start + chunk_size, n + 2)\n",
    "        L_prev, L = _log_Q_chunk(m_start, m_end, logb, L_prev, L)\n",
    "        m_start = m_end\n",
    "        temp_filename = f\"{filename}.{os.getpid()}.tmp\"\n",
    "        np.savez(temp_filename, m_start=m_start, L_prev=L_prev, L=L)\n",
    "        os.replace(temp_filename, filename)\n",
    "\n",
    "    logH = L_prev[n]\n",
    "    log_poch = _compute_log_poch(n, logb)\n",
    "    return (n * (n + 1) // 2) * logb - 2.0 * log_poch + logH\n",
    "\n",
    "@numba.njit\n",
    "def _log_Q_all_chunk(m_start, m_end, logb, L_prev, L, res, log_poch):\n",
    "    for m in range(m_start, m_end):\n",
    "        L[m - 1] = logsumexp_array(L_prev[:m - 1])\n",
    "        log1mbpow = log1mexp_neg((m - 1) * logb)\n",
    "        for i in range(m - 1, 0, -1):\n",
    "            t1 = logb + L[i]\n",
    "            t2 = (1 - i) * logb + log1mbpow + L_prev[i - 1]\n",
    "            L[i - 1] = logsumexp2(t1, t2)\n",
    "        temp = L_prev\n",
    "        L_prev = L\n",
    "        L = temp\n",
    "        num = m - 1\n",
    "        logH_num = L_prev[num]\n",
    "        log_poch += log1mexp_neg(num * logb)\n",
    "        res[num] = (num * (num + 1) / 2.0) * logb - 2.0 * log_poch + logH_num\n",
    "    return L_prev, L, res, log_poch\n",
    "\n",
    "def log_Q_all(n, b):\n",
    "    if not (0.0 < b < 1.0):\n",
    "        raise ValueError(\"b must lie in (0,1)\")\n",
    "    logb = math.log(b)\n",
    "    filename = f\"log_Q_all_n_{n}_b_{b}.npz\"\n",
    "    if os.path.exists(filename):\n",
    "        try:\n",
    "            data = np.load(filename)\n",
    "            m_start = int(data['m_start'])\n",
    "            L_prev = data['L_prev']\n",
    "            L = data['L']\n",
    "            res = data['res']\n",
    "            log_poch = float(data['log_poch'])\n",
    "        except Exception:\n",
    "            m_start = 2\n",
    "            L_prev = np.zeros(n + 2, dtype=np.float64)\n",
    "            L = np.zeros(n + 2, dtype=np.float64)\n",
    "            res = np.zeros(n + 1, dtype=np.float64)\n",
    "            log_poch = 0.0\n",
    "    else:\n",
    "        m_start = 2\n",
    "        L_prev = np.zeros(n + 2, dtype=np.float64)\n",
    "        L = np.zeros(n + 2, dtype=np.float64)\n",
    "        res = np.zeros(n + 1, dtype=np.float64)\n",
    "        log_poch = 0.0\n",
    "\n",
    "    chunk_size = 50000\n",
    "    while m_start < n + 2:\n",
    "        m_end = min(m_start + chunk_size, n + 2)\n",
    "        L_prev, L, res, log_poch = _log_Q_all_chunk(m_start, m_end, logb, L_prev, L, res, log_poch)\n",
    "        m_start = m_end\n",
    "        temp_filename = f\"{filename}.{os.getpid()}.tmp\"\n",
    "        np.savez(temp_filename, m_start=m_start, L_prev=L_prev, L=L, res=res, log_poch=log_poch)\n",
    "        os.replace(temp_filename, filename)\n",
    "    return res\n"
]

# The first cell should be the one to replace
for i, cell in enumerate(nb['cells']):
    if cell['cell_type'] == 'code' and "def log_Q_all(n, b):" in "".join(cell['source']):
        nb['cells'][i]['source'] = new_source
        break

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Notebook updated successfully.")
