import json

notebook_path = "/home/jonas/Documents/GitHub/HarmonicFermions/Jupyter/JonasPolyConv-opt.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

new_source_cell1 = [
    "import math\n",
    "import numpy as np\n",
    "import numba\n",
    "import sqlite3\n",
    "import os\n",
    "import time\n",
    "\n",
    "def init_polyconv_db(db_name='recursions_polyconv.db'):\n",
    "    try:\n",
    "        conn = sqlite3.connect(db_name, timeout=60.0)\n",
    "        c = conn.cursor()\n",
    "        c.execute('''CREATE TABLE IF NOT EXISTS polyconv_states\n",
    "                     (n INTEGER, d INTEGER, b REAL, k_start INTEGER, logZ BLOB, prev_logZn REAL, small_count INTEGER, cumulative_capacity REAL,\n",
    "                     PRIMARY KEY (n, d, b))''')\n",
    "        conn.commit()\n",
    "        conn.close()\n",
    "    except Exception:\n",
    "        pass\n",
    "\n",
    "def save_polyconv_state(n, d, b, k_start, logZ, prev_logZn, small_count, cumulative_capacity, db_name='recursions_polyconv.db'):\n",
    "    for _ in range(5):\n",
    "        try:\n",
    "            conn = sqlite3.connect(db_name, timeout=60.0)\n",
    "            c = conn.cursor()\n",
    "            c.execute('''INSERT OR REPLACE INTO polyconv_states (n, d, b, k_start, logZ, prev_logZn, small_count, cumulative_capacity)\n",
    "                         VALUES (?, ?, ?, ?, ?, ?, ?, ?)''', \n",
    "                      (n, d, b, k_start, logZ.tobytes(), prev_logZn, small_count, cumulative_capacity))\n",
    "            conn.commit()\n",
    "            conn.close()\n",
    "            break\n",
    "        except sqlite3.OperationalError:\n",
    "            time.sleep(2)\n",
    "\n",
    "def load_polyconv_state(n, d, b, db_name='recursions_polyconv.db'):\n",
    "    for _ in range(5):\n",
    "        try:\n",
    "            conn = sqlite3.connect(db_name, timeout=60.0)\n",
    "            c = conn.cursor()\n",
    "            c.execute('''SELECT k_start, logZ, prev_logZn, small_count, cumulative_capacity FROM polyconv_states WHERE n=? AND b=? AND d=?''', (n, b, d))\n",
    "            row = c.fetchone()\n",
    "            conn.close()\n",
    "            if row is None:\n",
    "                return None\n",
    "            k_start = row[0]\n",
    "            logZ = np.frombuffer(row[1], dtype=np.float64).copy()\n",
    "            prev_logZn = row[2]\n",
    "            small_count = row[3]\n",
    "            cumulative_capacity = row[4]\n",
    "            return k_start, logZ, prev_logZn, small_count, cumulative_capacity\n",
    "        except sqlite3.OperationalError:\n",
    "            time.sleep(2)\n",
    "    return None\n",
    "\n",
    "@numba.njit\n",
    "def logaddexp(a, b):\n",
    "    if a == -np.inf:\n",
    "        return b\n",
    "    if b == -np.inf:\n",
    "        return a\n",
    "    if a > b:\n",
    "        return a + math.log1p(math.exp(b - a))\n",
    "    else:\n",
    "        return b + math.log1p(math.exp(a - b))\n",
    "\n",
    "@numba.njit\n",
    "def level_degeneracy_numba(d, k):\n",
    "    if k == 0: return 1.0\n",
    "    if d == 1: return 1.0\n",
    "    res = 1.0\n",
    "    for i in range(1, k + 1):\n",
    "        res = res * (d + k - i) / i\n",
    "    return res\n",
    "\n",
    "@numba.njit\n",
    "def log_binom(n, k):\n",
    "    if k < 0 or k > n:\n",
    "        return -np.inf\n",
    "    return math.lgamma(n + 1) - math.lgamma(k + 1) - math.lgamma(n - k + 1)\n",
    "\n",
    "@numba.njit\n",
    "def _polyconv_fixed_chunk(k_start, k_end, logZ, d, logb, n):\n",
    "    for k in range(k_start, k_end):\n",
    "        g_float = level_degeneracy_numba(d, k)\n",
    "        mmax = int(min(g_float, float(n)))\n",
    "        logwk = k * logb\n",
    "        \n",
    "        logC = np.zeros(mmax + 1, dtype=np.float64)\n",
    "        for m in range(1, mmax + 1):\n",
    "            logC[m] = log_binom(g_float, m) + m * logwk\n",
    "            \n",
    "        old = logZ.copy()\n",
    "        for r in range(n + 1):\n",
    "            s = -np.inf\n",
    "            upper = min(r, mmax)\n",
    "            for m in range(upper + 1):\n",
    "                if old[r - m] != -np.inf:\n",
    "                    s = logaddexp(s, logC[m] + old[r - m])\n",
    "            logZ[r] = s\n",
    "    return logZ, k_end\n",
    "\n",
    "@numba.njit\n",
    "def _polyconv_adaptive_chunk(k_start, k_end, logZ, d, logb, n, tol, consecutive_small, cumulative_capacity, prev_logZn, small_count):\n",
    "    stop_reached = False\n",
    "    for k in range(k_start, k_end):\n",
    "        g_float = level_degeneracy_numba(d, k)\n",
    "        mmax = int(min(g_float, float(n)))\n",
    "        logwk = k * logb\n",
    "        \n",
    "        logC = np.zeros(mmax + 1, dtype=np.float64)\n",
    "        for m in range(1, mmax + 1):\n",
    "            logC[m] = log_binom(g_float, m) + m * logwk\n",
    "            \n",
    "        old = logZ.copy()\n",
    "        for r in range(n + 1):\n",
    "            s = -np.inf\n",
    "            upper = min(r, mmax)\n",
    "            for m in range(upper + 1):\n",
    "                if old[r - m] != -np.inf:\n",
    "                    s = logaddexp(s, logC[m] + old[r - m])\n",
    "            logZ[r] = s\n",
    "\n",
    "        cumulative_capacity += g_float\n",
    "\n",
    "        if cumulative_capacity >= n:\n",
    "            curr = logZ[n]\n",
    "            if prev_logZn != -np.inf and curr != -np.inf:\n",
    "                delta_log = abs(curr - prev_logZn)\n",
    "                if delta_log <= tol:\n",
    "                    small_count += 1\n",
    "                else:\n",
    "                    small_count = 0\n",
    "            prev_logZn = curr\n",
    "\n",
    "            if small_count >= consecutive_small:\n",
    "                stop_reached = True\n",
    "                k_start = k + 1\n",
    "                break\n",
    "    else:\n",
    "        k_start = k_end\n",
    "        \n",
    "    return logZ, cumulative_capacity, prev_logZn, small_count, stop_reached, k_start\n",
    "\n",
    "def fermion_logZ_numeric(tau, N, n, d, max_shell=None, tol=1e-4,\n",
    "                         consecutive_small=8, safety_cap=100000,\n",
    "                         return_all=False):\n",
    "    if N <= 0:\n",
    "        raise ValueError(\"N must be a positive integer.\")\n",
    "    if n < 0:\n",
    "        raise ValueError(\"n must be a nonnegative integer.\")\n",
    "    if d <= 0:\n",
    "        raise ValueError(\"d must be a positive integer.\")\n",
    "    if tau < 0:\n",
    "        raise ValueError(\"tau must be nonnegative.\")\n",
    "    if max_shell is not None and max_shell < 0:\n",
    "        raise ValueError(\"max_shell must be None or a nonnegative integer.\")\n",
    "\n",
    "    epsilon = tau / N\n",
    "    zeta = 1.0 + 0.5 * epsilon * epsilon\n",
    "    u = math.log(zeta + math.sqrt(zeta * zeta - 1.0))\n",
    "    b = math.exp(-N * u)\n",
    "    logb = -N * u\n",
    "\n",
    "    if n == 0:\n",
    "        logZ = [-math.inf] * (n + 1)\n",
    "        logZ[0] = 0.0\n",
    "        info = {\n",
    "            \"epsilon\": epsilon,\n",
    "            \"zeta\": zeta,\n",
    "            \"u\": u,\n",
    "            \"b\": b,\n",
    "            \"logb\": logb,\n",
    "            \"shells_used\": 0,\n",
    "        }\n",
    "        return (0.0, logZ, info) if return_all else 0.0\n",
    "\n",
    "    init_polyconv_db()\n",
    "    state = load_polyconv_state(n, d, b)\n",
    "    if state is not None:\n",
    "        k_start, logZ, prev_logZn, small_count, cumulative_capacity = state\n",
    "    else:\n",
    "        k_start = 0\n",
    "        logZ = np.full(n + 1, -np.inf, dtype=np.float64)\n",
    "        logZ[0] = 0.0\n",
    "        prev_logZn = -np.inf\n",
    "        small_count = 0\n",
    "        cumulative_capacity = 0.0\n",
    "\n",
    "    chunk_size = 50000\n",
    "    stop_reached = False\n",
    "\n",
    "    if max_shell is not None:\n",
    "        target_cap = max_shell + 1\n",
    "        is_adaptive = False\n",
    "    else:\n",
    "        target_cap = safety_cap + 1\n",
    "        is_adaptive = True\n",
    "\n",
    "    while k_start < target_cap and not stop_reached:\n",
    "        k_end = min(k_start + chunk_size, target_cap)\n",
    "        if is_adaptive:\n",
    "            logZ, cumulative_capacity, prev_logZn, small_count, stop_reached, k_start = _polyconv_adaptive_chunk(\n",
    "                k_start, k_end, logZ, d, logb, n, tol, consecutive_small, cumulative_capacity, prev_logZn, small_count\n",
    "            )\n",
    "        else:\n",
    "            logZ, k_start = _polyconv_fixed_chunk(k_start, k_end, logZ, d, logb, n)\n",
    "            \n",
    "        save_polyconv_state(n, d, b, k_start, logZ, prev_logZn, small_count, cumulative_capacity)\n",
    "\n",
    "    if is_adaptive and not stop_reached:\n",
    "        raise RuntimeError(\n",
    "            \"Adaptive truncation did not converge. \"\n",
    "            \"Try increasing safety_cap or set max_shell explicitly.\"\n",
    "        )\n",
    "\n",
    "    shells_used = k_start\n",
    "\n",
    "    logZ_list = [float(x) if x != -np.inf else -math.inf for x in logZ]\n",
    "\n",
    "    if return_all:\n",
    "        info = {\n",
    "            \"epsilon\": epsilon,\n",
    "            \"zeta\": zeta,\n",
    "            \"u\": u,\n",
    "            \"b\": b,\n",
    "            \"logb\": logb,\n",
    "            \"shells_used\": shells_used,\n",
    "        }\n",
    "        return logZ_list[n], logZ_list, info\n",
    "\n",
    "    return logZ_list[n]\n"
]

new_source_cell3 = [
    "import matplotlib.pyplot as plt\n",
    "from joblib import Parallel, delayed\n",
    "\n",
    "def make_tau_grid(tau_start, tau_end, tau_step):\n",
    "    if tau_step <= 0:\n",
    "        raise ValueError(\"tau_step must be positive.\")\n",
    "    if tau_end < tau_start:\n",
    "        raise ValueError(\"tau_end must be >= tau_start.\")\n",
    "\n",
    "    taus = []\n",
    "    tau = tau_start\n",
    "    while tau <= tau_end + 1e-15:\n",
    "        taus.append(round(tau, 12))\n",
    "        tau += tau_step\n",
    "    return taus\n",
    "\n",
    "def finite_difference_user_sign(x, y):\n",
    "    if len(x) != len(y):\n",
    "        raise ValueError(\"x and y must have the same length.\")\n",
    "    if len(x) < 2:\n",
    "        raise ValueError(\"Need at least 2 points.\")\n",
    "\n",
    "    x_fd = x[:-1]\n",
    "    y_fd = []\n",
    "    for i in range(len(x) - 1):\n",
    "        dx = x[i + 1] - x[i]\n",
    "        y_fd.append((y[i] - y[i + 1]) / dx)\n",
    "    return x_fd, y_fd\n",
    "\n",
    "def compute_logZ_worker(tau, N, n, d, logZ_kwargs):\n",
    "    return fermion_logZ_numeric(tau=tau, N=N, n=n, d=d, **logZ_kwargs)\n",
    "\n",
    "def plot_logZ_and_fd_multiN(tau_start, tau_end, tau_step, n, d, N_list,\n",
    "                            show_logZ=True, show_fd=True, **logZ_kwargs):\n",
    "    taus = make_tau_grid(tau_start, tau_end, tau_step)\n",
    "    results = {}\n",
    "\n",
    "    for N in N_list:\n",
    "        logZ_vals = Parallel(n_jobs=-1)(\n",
    "            delayed(compute_logZ_worker)(tau, N, n, d, logZ_kwargs)\n",
    "            for tau in taus\n",
    "        )\n",
    "        tau_fd, fd_vals = finite_difference_user_sign(taus, logZ_vals)\n",
    "\n",
    "        results[N] = {\n",
    "            \"taus\": taus,\n",
    "            \"logZ\": logZ_vals,\n",
    "            \"tau_fd\": tau_fd,\n",
    "            \"fd\": fd_vals,\n",
    "        }\n",
    "\n",
    "    if show_logZ:\n",
    "        plt.figure(figsize=(8, 5))\n",
    "        for N in N_list:\n",
    "            plt.plot(results[N][\"taus\"], results[N][\"logZ\"], marker=\".\", label=f\"N={N}\")\n",
    "        plt.xlabel(\"tau\")\n",
    "        plt.ylabel(\"log Z_n\")\n",
    "        plt.title(f\"log Z_n vs tau (n={n}, d={d})\")\n",
    "        plt.grid(True)\n",
    "        plt.legend()\n",
    "        plt.show()\n",
    "\n",
    "    if show_fd:\n",
    "        plt.figure(figsize=(8, 5))\n",
    "        for N in N_list:\n",
    "            plt.plot(results[N][\"tau_fd\"], results[N][\"fd\"], marker=\".\", label=f\"N={N}\")\n",
    "        plt.xlabel(\"tau\")\n",
    "        plt.ylabel(\"(log Z(tau) - log Z(tau + dt)) / dt\")\n",
    "        plt.title(f\"Finite difference vs tau (n={n}, d={d})\")\n",
    "        plt.grid(True)\n",
    "        plt.legend()\n",
    "        plt.show()\n",
    "\n",
    "    return results\n"
]

for i, cell in enumerate(nb['cells']):
    src = "".join(cell['source'])
    if "def fermion_logZ_numeric(" in src:
        nb['cells'][i]['source'] = new_source_cell1
    elif "def plot_logZ_and_fd_multiN(" in src:
        nb['cells'][i]['source'] = new_source_cell3

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("JonasPolyConv-opt updated successfully.")
